name: Build and Release MailLobbyer for OSX

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  build-OSX:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: macos-13
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'

    - name: Install ElectronNET.CLI
      run: dotnet tool install ElectronNET.CLI -g

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Restore NuGet packages
      run: dotnet restore
      working-directory: src/MailLobbyer

    - name: Build Electron.NET app for OSX
      run: electronize build /target osx
      working-directory: src/MailLobbyer

    - name: Create zip file
      run: |
        zip -r ML-OSX-${{ GitHub.sha }}.zip src/MailLobbyer/bin/desktop

    - name: Upload artifact to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ML-OSX-${{ GitHub.sha }}.zip
        tag_name: ${{ github.ref }}
        name: ${{ github.event.pull_request.title }}
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION }}
