name: Build MailLobbyer for OSX.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-OSX:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  

    - name: Install ElectronNET.CLI
      run: dotnet tool install ElectronNET.CLI -g

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  

    - name: Restore NuGet packages
      run: dotnet restore
      working-directory: src/MailLobbyer

    - name: Build Electron.NET app for OSX
      run: electronize build /target osx
      working-directory: src/MailLobbyer

    - name: Zip built package
      run: |
        mkdir -p builds
        zip -r builds/ML-OSX-$(date +'%Y%m%d').zip src/MailLobbyer/bin/desktop

    - name: Clear bin/desktop
      run: rm -rf src/MailLobbyer/bin/desktop/*
        
    - name: Upload built package
      uses: actions/upload-artifact@v2
      with:
        name: ML-OSX-$(date +'%Y%m%d')
        path: builds/ML-OSX-$(date +'%Y%m%d').zip




